from pathlib import Path
import base64

path = Path(r"D:\Het\demo2\static\js\page3.js")
text = path.read_text(encoding="utf-8")

old = base64.b64decode("ICBpZiAoSVNfT1BFUkFUT1JfUkVBRF9PTkxZKSB7CiAgICAvLyBPcGVyYXRvciBjYW4gb25seSBjb21wbGV0ZSB0aGVpciBhc3NpZ25lZCBwcm9jZXNzCiAgICBjb25zdCBjbGlja2VkUHJvYyA9IGRlY29kZVVSSUNvbXBvbmVudChwaWxsRWwuZGF0YXNldC5wcm9jZXNzIHx8ICIiKTsKICAgIGNvbnN0IGlJZHggPSBwYXJzZUludChwaWxsRWwuZGF0YXNldC5paWR4KTsKICAgIGNvbnN0IGl0ZW0gPSBjdXJyZW50RGF0YT8uaXRlbXM/LltpSWR4XSB8fCB7fTsKICAgIGlmICghQXJyYXkuaXNBcnJheSh3aW5kb3cubXlBY2Nlc3NpYmxlUHJvY2Vzc2VzKSkgcmV0dXJuOwogICAgY29uc3QgaXNBc3NpZ25lZCA9IHdpbmRvdy5teUFjY2Vzc2libGVQcm9jZXNzZXMuc29tZSgKICAgICAgcCA9PiBwLnRyaW0oKS50b0xvd2VyQ2FzZSgpID09PSBjbGlja2VkUHJvYy50cmltKCkudG9Mb3dlckNhc2UoKQogICAgKTsKICAgIGlmICghaXNBc3NpZ25lZCkgewogICAgICBzaG93VG9hc3QoIllvdSBhcmUgbm90IGFzc2lnbmVkIHRvIHRoaXMgcHJvY2Vzcy4iLCAiZXJyb3IiKTsKICAgICAgcmV0dXJuOwogICAgfQogICAgY29uc3QgZ2xvYmFsSWR4ID0gb3BlcmF0b3JDYXJkcy5maW5kSW5kZXgoYyA9PiBjLmpvYl9jYXJkX25vID09PSBkZWNvZGVVUklDb21wb25lbnQocGlsbEVsLmRhdGFzZXQuamNubyB8fCAiIikpOwogICAgaWYgKGdsb2JhbElkeCA+PSAwKSB7CiAgICAgIG9wZW5PcGVyYXRvckNvbXBsZXRlTW9kYWwoZ2xvYmFsSWR4KTsKICAgIH0gZWxzZSB7CiAgICAgIHNob3dUb2FzdCgiSm9iIGNhcmQgbm90IGZvdW5kIGluIHlvdXIgcXVldWUuIiwgImVycm9yIik7CiAgICB9CiAgICByZXR1cm47CiAgfQo=").decode("utf-8")
new = base64.b64decode("ICBpZiAoSVNfT1BFUkFUT1JfUkVBRF9PTkxZKSB7CiAgICAvLyBPUEVSQVRPUl9TRUFSQ0hfQUNUSU9OX0ZJWF9WMQogICAgLy8gT3BlcmF0b3IgcXVldWUgaXMgYWxyZWFkeSBmaWx0ZXJlZCBieSBhc3NpZ25lZCBwcm9jZXNzLgogICAgLy8gU2VhcmNoIHJlc3VsdHMgdGhlcmVmb3JlIHJlc29sdmUgYmFjayB0byB0aGF0IHF1ZXVlIGluc3RlYWQKICAgIC8vIG9mIGRlcGVuZGluZyBvbiB3aW5kb3cubXlBY2Nlc3NpYmxlUHJvY2Vzc2VzLgogICAgY29uc3QgY2xpY2tlZFByb2MgPSBkZWNvZGVVUklDb21wb25lbnQoCiAgICAgIHBpbGxFbC5kYXRhc2V0LnByb2Nlc3MgfHwgIiIKICAgICkudHJpbSgpOwoKICAgIGNvbnN0IHNlYXJjaGVkSmMgPSBkZWNvZGVVUklDb21wb25lbnQoCiAgICAgIHBpbGxFbC5kYXRhc2V0Lmpjbm8gfHwgIiIKICAgICkudHJpbSgpOwoKICAgIGNvbnN0IGlJZHggPSBwYXJzZUludChwaWxsRWwuZGF0YXNldC5paWR4KTsKICAgIGNvbnN0IGl0ZW0gPSBjdXJyZW50RGF0YT8uaXRlbXM/LltpSWR4XSB8fCB7fTsKICAgIGNvbnN0IHNlYXJjaGVkSXRlbSA9IFN0cmluZyhpdGVtLml0ZW1fbmFtZSB8fCAiIikudHJpbSgpOwoKICAgIGxldCBnbG9iYWxJZHggPSBvcGVyYXRvckNhcmRzLmZpbmRJbmRleChmdW5jdGlvbihjYXJkKSB7CiAgICAgIGNvbnN0IHNhbWVKYyA9CiAgICAgICAgU3RyaW5nKGNhcmQ/LmpvYl9jYXJkX25vIHx8ICIiKS50cmltKCkgPT09IHNlYXJjaGVkSmM7CgogICAgICBjb25zdCBjYXJkUHJvY2VzcyA9IFN0cmluZygKICAgICAgICBjYXJkPy5jdXJyZW50X3Byb2Nlc3MgfHwgY2FyZD8ud2lwX3N0YXR1cyB8fCAiIgogICAgICApLnRyaW0oKS50b0xvd2VyQ2FzZSgpOwoKICAgICAgY29uc3Qgc2FtZVByb2Nlc3MgPQogICAgICAgIGNhcmRQcm9jZXNzID09PSBjbGlja2VkUHJvYy50b0xvd2VyQ2FzZSgpOwoKICAgICAgY29uc3QgY2FyZEl0ZW0gPSBTdHJpbmcoY2FyZD8uaXRlbV9uYW1lIHx8ICIiKS50cmltKCk7CiAgICAgIGNvbnN0IHNhbWVJdGVtID0KICAgICAgICAhc2VhcmNoZWRJdGVtIHx8ICFjYXJkSXRlbSB8fCBjYXJkSXRlbSA9PT0gc2VhcmNoZWRJdGVtOwoKICAgICAgcmV0dXJuIHNhbWVKYyAmJiBzYW1lUHJvY2VzcyAmJiBzYW1lSXRlbTsKICAgIH0pOwoKICAgIC8vIEZhbGxiYWNrIGZvciBvbGRlciBxdWV1ZSBwYXlsb2FkcyB3aXRoIGluY29tcGxldGUgaXRlbS9wcm9jZXNzIGZpZWxkcy4KICAgIGlmIChnbG9iYWxJZHggPCAwKSB7CiAgICAgIGdsb2JhbElkeCA9IG9wZXJhdG9yQ2FyZHMuZmluZEluZGV4KGZ1bmN0aW9uKGNhcmQpIHsKICAgICAgICByZXR1cm4gU3RyaW5nKGNhcmQ/LmpvYl9jYXJkX25vIHx8ICIiKS50cmltKCkgPT09IHNlYXJjaGVkSmM7CiAgICAgIH0pOwogICAgfQoKICAgIGlmIChnbG9iYWxJZHggPj0gMCkgewogICAgICBvcGVuT3BlcmF0b3JDb21wbGV0ZU1vZGFsKGdsb2JhbElkeCk7CiAgICB9IGVsc2UgewogICAgICBzaG93VG9hc3QoCiAgICAgICAgIlRoaXMgSm9iIENhcmQgaXMgbm90IGFjdGl2ZSBpbiB5b3VyIGFzc2lnbmVkIG9wZXJhdG9yIHF1ZXVlLiIsCiAgICAgICAgImVycm9yIgogICAgICApOwogICAgfQoKICAgIHJldHVybjsKICB9Cg==").decode("utf-8")

count = text.count(old)
if count != 1:
    raise SystemExit(
        f"FAIL - expected operator search-action block exactly once, found {count}"
    )

text = text.replace(old, new, 1)

for token in (
    "OPERATOR_SEARCH_ACTION_FIX_V1",
    "openOperatorCompleteModal(globalIdx);",
    "This Job Card is not active in your assigned operator queue.",
):
    if token not in text:
        raise SystemExit(f"FAIL - missing verification token: {token}")

path.write_text(text, encoding="utf-8")

print("PASS - operator search action no longer depends on myAccessibleProcesses")
print("PASS - searched JC resolves against the operator assigned queue")
print("PASS - process/item matching added with JC fallback")
print("PASS - no backend or database change executed")
